parameters:
  toolchain: stable
  name: test
  steps: []
  features: []
jobs:
  - job: ${{ parameters.name }}
    displayName: test (${{parameters.toolchain}})
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-16.04
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
    pool:
      vmImage: $(vmImage)

    steps:
      - template: steps-install-rust.yml
        parameters:
          toolchain: ${{ parameters.toolchain }}
      - script: |
          cargo test --all --all-targets --features "${{ join(' ', parameters.features) }}"
        displayName: cargo test --all --all-targets
      - ${{ each step in parameters.steps }}:
          - ${{ each pair in step }}:
              ${{ pair.key }}: ${{ pair.value }}
